name: PR

on:
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno fmt --check
      - run: deno lint

  compile:
    needs: test

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: mkdir -p ./dist/
      - run: deno compile --target aarch64-apple-darwin --frozen --reload --output dist/toy-aarch64-apple-darwin -RW main.ts
      - run: deno compile --target x86_64-unknown-linux-gnu --frozen --reload --output dist/toy-x86_64-unknown-linux-gnu -RW main.ts
      - run: deno compile --target x86_64-pc-windows-msvc --frozen --reload --output dist/toy-x86_64-pc-windows-msvc.exe -RW main.ts
